version: "3"
services:
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env.db

  db-admin:
    build: 
      context: .
      dockerfile: Dockerfile-pgadmin
    env_file: 
      - .env.db
    depends_on: 
      - db
    ports: 
      - "8080:80"

volumes:
  dbdata:

